name: Dependency Update Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'go.mod'
      - 'go.sum'

jobs:
  lint:
    name: 🧹 Run Go Lint
    uses: ./.github/workflows/go-lint.yml

  test:
    name: 🧪 Run Go Tests
    uses: ./.github/workflows/go-test.yml

  dependency-update-summary:
    name: 📊 Dependency update test summary
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: 📊 Dependency update test summary
        run: |
          echo "## 📋 Dependency Update Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Lint result: ${{ needs.lint.result }}" >> $GITHUB_STEP_SUMMARY
          echo "✅ Test result: ${{ needs.test.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🎉 Dependency update validation complete!"